pygments: true
lsi: false
paginate: 10
#baseurl: bpcl
permalink: pretty
sitename: bpcl
feedburner.id: 'beatspixelscodelife/kJuy'
google_analytics.account: 'UA-288188-6'

#url: http://beatspixelscodelife.com

exclude: tmp, test, bin
